import { collectSchemaSections } from "../sections/collect-schema-sections.js";
import type { SchemaGraph, SchemaTable } from "../schema/schema-graph.js";
import { generateMermaidErd } from "./generate-mermaid-erd.js";

export interface GenerateTypeormMarkdownOptions {
  title?: string;
}

export const generateTypeormMarkdown = (
  graph: SchemaGraph,
  options: GenerateTypeormMarkdownOptions = {},
): string => {
  const title = options.title ?? "TypeORM Schema";
  const sections = collectSchemaSections(graph);
  const lines: string[] = [
    `# ${title}`,
    "",
    "> Generated by `typeorm-docs-mcp`.",
    "",
    "## Table of Contents",
    "",
    ...sections.map((section) => `- [${section.name}](#${anchor(section.name)})`),
    "",
  ];

  for (const section of sections) {
    lines.push(`## ${section.name}`, "");
    if (section.erdTables.length > 0) lines.push(generateMermaidErd(graph, { tables: section.erdTables }), "");
    for (const table of section.descriptionTables) {
      lines.push(writeTable(table), "");
    }
  }

  return lines.join("\n").trimEnd() + "\n";
};

const writeTable = (table: SchemaTable): string => {
  const lines = [`### \`${table.name}\``];
  if (table.description.length > 0) lines.push("", table.description);
  lines.push("", "| Column | Type | Key | Nullable | Description |", "|---|---|---|---|---|");
  for (const column of table.columns) {
    lines.push(
      `| \`${column.name}\` | \`${column.type}\` | ${columnKeys(column)} | ${
        column.nullable ? "Yes" : "No"
      } | ${column.description} |`,
    );
  }
  if (table.relations.length > 0) {
    lines.push("", "#### Relations", "");
    for (const relation of table.relations) {
      const target = relation.targetTable ?? relation.targetEntity;
      const suffix = relation.description.length > 0 ? `: ${relation.description}` : "";
      lines.push(`- \`${relation.propertyName}\` → \`${target}\` (${relation.type})${suffix}`);
    }
  }
  return lines.join("\n");
};

const columnKeys = (column: { primaryKey: boolean; foreignKey: boolean; unique: boolean }): string =>
  [column.primaryKey ? "PK" : "", column.foreignKey ? "FK" : "", column.unique ? "UK" : ""]
    .filter((value) => value.length > 0)
    .join(",");

const anchor = (value: string): string => value.toLowerCase().replace(/\s+/g, "-");
